[project]
name = "anagram-finder"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "aiostream>=0.6.4",
    "fastapi>=0.115.10",
    "uvicorn>=0.34.0",
    "websockets>=15.0",
]
